"""Add protection device table

Revision ID: 6f3194cd9dea
Revises: c32a8205f37b
Create Date: 2026-10-07 10:36:52.323215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f3194cd9dea'
down_revision = 'c32a8205f37b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('protection_device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_type', sa.String(length=100), nullable=False),
    sa.Column('rating', sa.String(length=50), nullable=False),
    sa.Column('poles', sa.Integer(), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('stock_quantity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('protection_device')
    # ### end Alembic commands ###
