"""Add labour table

Revision ID: 739ef8795df8
Revises: dad41f7675cd
Create Date: 2026-10-07 11:08:14.457043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '739ef8795df8'
down_revision = 'dad41f7675cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labour',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('calculation_method', sa.String(length=50), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('labour')
    # ### end Alembic commands ###
