"""Add cable table

Revision ID: 94c2684ccada
Revises: d4cc70299e86
Create Date: 2026-10-07 10:28:59.240267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94c2684ccada'
down_revision = 'd4cc70299e86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cable_type', sa.String(length=100), nullable=False),
    sa.Column('size', sa.String(length=50), nullable=False),
    sa.Column('colour', sa.String(length=50), nullable=False),
    sa.Column('function', sa.String(length=50), nullable=False),
    sa.Column('coil_length', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('stock_quantity', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cable')
    # ### end Alembic commands ###
