"""Add circuit table

Revision ID: c32a8205f37b
Revises: 94c2684ccada
Create Date: 2026-10-07 10:32:24.741873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c32a8205f37b'
down_revision = '94c2684ccada'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circuit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('circuit_name', sa.String(length=100), nullable=False),
    sa.Column('circuit_type', sa.String(length=100), nullable=False),
    sa.Column('connected_load', sa.Float(), nullable=True),
    sa.Column('design_load', sa.Float(), nullable=True),
    sa.Column('design_current', sa.Float(), nullable=True),
    sa.Column('cable_size', sa.String(length=50), nullable=True),
    sa.Column('protection_rating', sa.String(length=50), nullable=True),
    sa.Column('route_length', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('circuit')
    # ### end Alembic commands ###
