"""Add fitting table

Revision ID: d4cc70299e86
Revises: 19f349d0d1dd
Create Date: 2026-10-07 10:24:47.061246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4cc70299e86'
down_revision = '19f349d0d1dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fitting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('default_rating', sa.String(length=50), nullable=True),
    sa.Column('default_load', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fitting')
    # ### end Alembic commands ###
