"""Add material price table

Revision ID: dad41f7675cd
Revises: f7ecdf4a21df
Create Date: 2026-10-07 10:59:57.314033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dad41f7675cd'
down_revision = 'f7ecdf4a21df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_name', sa.String(length=150), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('supplier', sa.String(length=150), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('material_price')
    # ### end Alembic commands ###
